@ITAssetTracker.WebAPI_HostAddress = https://localhost:7149

PUT {{ITAssetTracker.WebAPI_HostAddress}}/api/assetassignment
Content-Type: application/json

{
      "id": 2,
      "assetId": 3,
      "employeeId": 4,
      "assignmentPeriod": {
        "start": "2027-02-10",
        "end": null
    }
}

###

GET {{ITAssetTracker.WebAPI_HostAddress}}/api/assetassignment/all

###
