// <auto-generated />
using System;
using ITAssetTracker.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITAssetTracker.Persistence.Migrations
{
    [DbContext(typeof(ITAssetTrackerContext))]
    [Migration("20260712130728_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WarrantyExpiryDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetProductId");

                    b.HasIndex("AssetStatusId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetProductId = 1,
                            AssetStatusId = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 163, DateTimeKind.Utc).AddTicks(4263),
                            Description = "Primary developer laptop",
                            Location = "London Office",
                            Name = "Dell Latitude Laptop",
                            Price = 1200m,
                            PurchaseDate = new DateOnly(2023, 1, 10),
                            SerialNumber = "DL5420-ABC123",
                            Tag = "10001",
                            WarrantyExpiryDate = new DateOnly(2026, 1, 10)
                        },
                        new
                        {
                            Id = 2,
                            AssetProductId = 2,
                            AssetStatusId = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 163, DateTimeKind.Utc).AddTicks(5522),
                            Description = "Finance department laptop",
                            Location = "Finance Office",
                            Name = "ThinkPad X1",
                            Price = 1400m,
                            PurchaseDate = new DateOnly(2023, 3, 12),
                            SerialNumber = "TPX1-DEF456",
                            Tag = "10002",
                            WarrantyExpiryDate = new DateOnly(2026, 3, 12)
                        },
                        new
                        {
                            Id = 3,
                            AssetProductId = 3,
                            AssetStatusId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 163, DateTimeKind.Utc).AddTicks(5524),
                            Description = "Spare executive laptop",
                            Location = "IT Storage",
                            Name = "MacBook Pro",
                            Price = 2400m,
                            PurchaseDate = new DateOnly(2024, 1, 20),
                            SerialNumber = "MBP-GHI789",
                            Tag = "10003",
                            WarrantyExpiryDate = new DateOnly(2027, 1, 20)
                        },
                        new
                        {
                            Id = 4,
                            AssetProductId = 5,
                            AssetStatusId = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 163, DateTimeKind.Utc).AddTicks(5524),
                            Description = "27 inch monitor",
                            Location = "London Office",
                            Name = "Dell Monitor",
                            Price = 350m,
                            PurchaseDate = new DateOnly(2023, 2, 1),
                            SerialNumber = "MON-XYZ111",
                            Tag = "10004",
                            WarrantyExpiryDate = new DateOnly(2026, 2, 1)
                        },
                        new
                        {
                            Id = 5,
                            AssetProductId = 9,
                            AssetStatusId = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 163, DateTimeKind.Utc).AddTicks(5525),
                            Description = "Core network switch",
                            Location = "Server Room",
                            Name = "Cisco Switch",
                            Price = 5000m,
                            PurchaseDate = new DateOnly(2022, 5, 1),
                            SerialNumber = "CSC-9300-222",
                            Tag = "10005",
                            WarrantyExpiryDate = new DateOnly(2027, 5, 1)
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AssetAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 154, DateTimeKind.Utc).AddTicks(6796),
                            EmployeeId = 4
                        },
                        new
                        {
                            Id = 2,
                            AssetId = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 154, DateTimeKind.Utc).AddTicks(7645),
                            EmployeeId = 3
                        },
                        new
                        {
                            Id = 3,
                            AssetId = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 154, DateTimeKind.Utc).AddTicks(7645),
                            EmployeeId = 4
                        },
                        new
                        {
                            Id = 4,
                            AssetId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 154, DateTimeKind.Utc).AddTicks(7646),
                            EmployeeId = 2
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("AssetProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 164, DateTimeKind.Utc).AddTicks(4804),
                            ManufacturerId = 1,
                            Name = "Latitude 5420"
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 164, DateTimeKind.Utc).AddTicks(5644),
                            ManufacturerId = 2,
                            Name = "ThinkPad X1 Carbon"
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 164, DateTimeKind.Utc).AddTicks(5645),
                            ManufacturerId = 3,
                            Name = "MacBook Pro 16"
                        },
                        new
                        {
                            Id = 4,
                            AssetTypeId = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 164, DateTimeKind.Utc).AddTicks(5645),
                            ManufacturerId = 4,
                            Name = "EliteDesk 800"
                        },
                        new
                        {
                            Id = 5,
                            AssetTypeId = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 164, DateTimeKind.Utc).AddTicks(5646),
                            ManufacturerId = 1,
                            Name = "UltraSharp 27 Monitor"
                        },
                        new
                        {
                            Id = 6,
                            AssetTypeId = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 164, DateTimeKind.Utc).AddTicks(5646),
                            ManufacturerId = 1,
                            Name = "PowerEdge R740"
                        },
                        new
                        {
                            Id = 7,
                            AssetTypeId = 5,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 164, DateTimeKind.Utc).AddTicks(5647),
                            ManufacturerId = 5,
                            Name = "Windows 11 Pro"
                        },
                        new
                        {
                            Id = 8,
                            AssetTypeId = 6,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 164, DateTimeKind.Utc).AddTicks(5647),
                            ManufacturerId = 5,
                            Name = "Microsoft 365 Business"
                        },
                        new
                        {
                            Id = 9,
                            AssetTypeId = 8,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 164, DateTimeKind.Utc).AddTicks(5648),
                            ManufacturerId = 6,
                            Name = "Cisco Catalyst 9300"
                        },
                        new
                        {
                            Id = 10,
                            AssetTypeId = 10,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 164, DateTimeKind.Utc).AddTicks(5648),
                            ManufacturerId = 7,
                            Name = "Galaxy Tab S8"
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssetStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 165, DateTimeKind.Utc).AddTicks(9628),
                            Name = "Available"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(163),
                            Name = "Assigned"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(164),
                            Name = "In Repair"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(164),
                            Name = "Retired"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(165),
                            Name = "Disposed"
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(7710),
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(8483),
                            Name = "Desktop"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(8484),
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(8484),
                            Name = "Server"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(8485),
                            Name = "Operating System"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(8485),
                            Name = "Productivity Software"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(8485),
                            Name = "Router"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(8486),
                            Name = "Switch"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(8486),
                            Name = "Smartphone"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 166, DateTimeKind.Utc).AddTicks(8487),
                            Name = "Tablet"
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 167, DateTimeKind.Utc).AddTicks(2720),
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 167, DateTimeKind.Utc).AddTicks(2721),
                            Name = "Software"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 167, DateTimeKind.Utc).AddTicks(2722),
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 167, DateTimeKind.Utc).AddTicks(2722),
                            Name = "Mobile Devices"
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 167, DateTimeKind.Utc).AddTicks(8253),
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 167, DateTimeKind.Utc).AddTicks(8254),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 167, DateTimeKind.Utc).AddTicks(8277),
                            Name = "Operations"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 167, DateTimeKind.Utc).AddTicks(8278),
                            Name = "Human Resources"
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DoB")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 170, DateTimeKind.Utc).AddTicks(7307),
                            DepartmentId = 1,
                            DoB = new DateOnly(1988, 5, 12),
                            FirstName = "Alex",
                            JobTitle = "System Administrator",
                            LastName = "Beker",
                            MiddleName = "",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 170, DateTimeKind.Utc).AddTicks(8517),
                            DepartmentId = 1,
                            DoB = new DateOnly(1992, 8, 20),
                            FirstName = "Michael",
                            JobTitle = "IT Support Technician",
                            LastName = "Beker",
                            MiddleName = "Davis",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 170, DateTimeKind.Utc).AddTicks(8519),
                            DepartmentId = 2,
                            DoB = new DateOnly(1985, 3, 14),
                            FirstName = "Emily",
                            JobTitle = "Finance Manager",
                            LastName = "Brown",
                            MiddleName = "",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 170, DateTimeKind.Utc).AddTicks(8519),
                            DepartmentId = 1,
                            DoB = new DateOnly(1991, 11, 3),
                            FirstName = "John",
                            JobTitle = "Software Engineer",
                            LastName = "Smith",
                            MiddleName = "",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 170, DateTimeKind.Utc).AddTicks(8520),
                            DepartmentId = 4,
                            DoB = new DateOnly(1994, 1, 25),
                            FirstName = "Sarah",
                            JobTitle = "HR Coordinator",
                            LastName = "Johnson",
                            MiddleName = "",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 173, DateTimeKind.Utc).AddTicks(1791),
                            Name = "Dell"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 173, DateTimeKind.Utc).AddTicks(1793),
                            Name = "Lenovo"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 173, DateTimeKind.Utc).AddTicks(1793),
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 173, DateTimeKind.Utc).AddTicks(1794),
                            Name = "HP"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 173, DateTimeKind.Utc).AddTicks(1794),
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 173, DateTimeKind.Utc).AddTicks(1795),
                            Name = "Cisco"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 173, DateTimeKind.Utc).AddTicks(1795),
                            Name = "Samsung"
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 173, DateTimeKind.Utc).AddTicks(7297),
                            Name = "Low"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 173, DateTimeKind.Utc).AddTicks(7298),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 173, DateTimeKind.Utc).AddTicks(7299),
                            Name = "High"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 173, DateTimeKind.Utc).AddTicks(7299),
                            Name = "Critical"
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Resolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Resolutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 174, DateTimeKind.Utc).AddTicks(3326),
                            Name = "Unresolved"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 174, DateTimeKind.Utc).AddTicks(3327),
                            Name = "Resolved"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 174, DateTimeKind.Utc).AddTicks(3328),
                            Name = "Repaired"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 174, DateTimeKind.Utc).AddTicks(3329),
                            Name = "Replaced"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 174, DateTimeKind.Utc).AddTicks(3352),
                            Name = "Configuration Changed"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 174, DateTimeKind.Utc).AddTicks(3352),
                            Name = "Software Updated"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 174, DateTimeKind.Utc).AddTicks(3353),
                            Name = "User Error"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 174, DateTimeKind.Utc).AddTicks(3354),
                            Name = "No Fault Found"
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 174, DateTimeKind.Utc).AddTicks(9316),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 174, DateTimeKind.Utc).AddTicks(9317),
                            Name = "IT Support"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 174, DateTimeKind.Utc).AddTicks(9318),
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 174, DateTimeKind.Utc).AddTicks(9318),
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResolutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("ResolutionId");

                    b.HasIndex("TicketStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetId = 1,
                            Comments = "Thermal diagnostics underway",
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 176, DateTimeKind.Utc).AddTicks(3725),
                            EmployeeId = 2,
                            PriorityId = 3,
                            ResolutionId = 1,
                            TicketStatusId = 2,
                            Title = "Laptop overheating"
                        },
                        new
                        {
                            Id = 2,
                            AssetId = 4,
                            Comments = "Refresh rate adjusted and issue resolved",
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 176, DateTimeKind.Utc).AddTicks(4638),
                            Description = "Screen flickers intermittently",
                            EmployeeId = 2,
                            PriorityId = 2,
                            ResolutionId = 5,
                            TicketStatusId = 4,
                            Title = "Monitor flickering"
                        },
                        new
                        {
                            Id = 3,
                            AssetId = 5,
                            Comments = "Awaiting maintenance window",
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 176, DateTimeKind.Utc).AddTicks(5238),
                            Description = "Switch intermittently disconnecting",
                            EmployeeId = 1,
                            PriorityId = 4,
                            ResolutionId = 1,
                            TicketStatusId = 2,
                            Title = "Network outage"
                        },
                        new
                        {
                            Id = 4,
                            AssetId = 2,
                            Comments = "Keyboard hardware repaired",
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 176, DateTimeKind.Utc).AddTicks(5239),
                            Description = "Several keys stopped functioning",
                            EmployeeId = 2,
                            PriorityId = 2,
                            ResolutionId = 3,
                            TicketStatusId = 4,
                            Title = "Keyboard not responding"
                        },
                        new
                        {
                            Id = 5,
                            AssetId = 3,
                            Comments = "Pending approval",
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 176, DateTimeKind.Utc).AddTicks(5240),
                            Description = "User requires Visual Studio installation",
                            EmployeeId = 1,
                            PriorityId = 1,
                            ResolutionId = 1,
                            TicketStatusId = 1,
                            Title = "Software installation request"
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.TicketStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TicketStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 177, DateTimeKind.Utc).AddTicks(4104),
                            Name = "Open"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 177, DateTimeKind.Utc).AddTicks(4106),
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 177, DateTimeKind.Utc).AddTicks(4106),
                            Name = "Resolved"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 177, DateTimeKind.Utc).AddTicks(4107),
                            Name = "Closed"
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 178, DateTimeKind.Utc).AddTicks(583),
                            PasswordHash = "hash_admin",
                            RoleId = 1,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 178, DateTimeKind.Utc).AddTicks(1380),
                            PasswordHash = "hash_support",
                            RoleId = 2,
                            UserName = "itsupport1"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 178, DateTimeKind.Utc).AddTicks(1380),
                            PasswordHash = "hash_manager",
                            RoleId = 3,
                            UserName = "manager1"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 178, DateTimeKind.Utc).AddTicks(1381),
                            PasswordHash = "hash_jsmith",
                            RoleId = 4,
                            UserName = "jsmith"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2026, 7, 12, 13, 7, 28, 178, DateTimeKind.Utc).AddTicks(1381),
                            PasswordHash = "hash_sjohnson",
                            RoleId = 4,
                            UserName = "sjohnson"
                        });
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Asset", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.AssetProduct", "AssetProducts")
                        .WithMany("Assets")
                        .HasForeignKey("AssetProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.AssetStatus", "AssetStatuses")
                        .WithMany("Assets")
                        .HasForeignKey("AssetStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetProducts");

                    b.Navigation("AssetStatuses");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetAssignment", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.Asset", "Asset")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.Employee", "Employee")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ITAssetTracker.Domain.ValueObjects.DateRange", "AssignmentPeriod", b1 =>
                        {
                            b1.Property<int>("AssetAssignmentId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateOnly?>("end")
                                .HasColumnType("TEXT")
                                .HasColumnName("ReturnedDate");

                            b1.Property<DateOnly>("start")
                                .HasColumnType("TEXT")
                                .HasColumnName("AssignedDate");

                            b1.HasKey("AssetAssignmentId");

                            b1.ToTable("AssetAssignments");

                            b1.WithOwner()
                                .HasForeignKey("AssetAssignmentId");

                            b1.HasData(
                                new
                                {
                                    AssetAssignmentId = 1,
                                    start = new DateOnly(2024, 1, 5)
                                },
                                new
                                {
                                    AssetAssignmentId = 2,
                                    start = new DateOnly(2024, 2, 10)
                                },
                                new
                                {
                                    AssetAssignmentId = 3,
                                    start = new DateOnly(2024, 1, 5)
                                },
                                new
                                {
                                    AssetAssignmentId = 4,
                                    end = new DateOnly(2024, 1, 4),
                                    start = new DateOnly(2023, 1, 1)
                                });
                        });

                    b.Navigation("Asset");

                    b.Navigation("AssignmentPeriod")
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetProduct", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.AssetType", "AssetType")
                        .WithMany("AssetProducts")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("AssetProducts")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetType", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.Category", "Category")
                        .WithMany("AssetTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Employee", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("ITAssetTracker.Domain.Entities.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ITAssetTracker.Domain.ValueObjects.DateRange", "EmploymentPeriod", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateOnly?>("end")
                                .HasColumnType("TEXT")
                                .HasColumnName("TerminationDate");

                            b1.Property<DateOnly>("start")
                                .HasColumnType("TEXT")
                                .HasColumnName("HireDate");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.HasData(
                                new
                                {
                                    EmployeeId = 1,
                                    start = new DateOnly(2018, 1, 10)
                                },
                                new
                                {
                                    EmployeeId = 2,
                                    start = new DateOnly(2021, 6, 1)
                                },
                                new
                                {
                                    EmployeeId = 3,
                                    start = new DateOnly(2017, 2, 15)
                                },
                                new
                                {
                                    EmployeeId = 4,
                                    start = new DateOnly(2020, 9, 1)
                                },
                                new
                                {
                                    EmployeeId = 5,
                                    start = new DateOnly(2022, 3, 10)
                                });
                        });

                    b.OwnsOne("ITAssetTracker.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.HasData(
                                new
                                {
                                    EmployeeId = 1,
                                    Value = "alex.admin@company.com"
                                },
                                new
                                {
                                    EmployeeId = 2,
                                    Value = "michael.davis@company.com"
                                },
                                new
                                {
                                    EmployeeId = 3,
                                    Value = "emily.brown@company.com"
                                },
                                new
                                {
                                    EmployeeId = 4,
                                    Value = "john.smith@company.com"
                                },
                                new
                                {
                                    EmployeeId = 5,
                                    Value = "sarah.johnson@company.com"
                                });
                        });

                    b.OwnsOne("ITAssetTracker.Domain.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.HasData(
                                new
                                {
                                    EmployeeId = 1,
                                    Value = "07111111111"
                                },
                                new
                                {
                                    EmployeeId = 2,
                                    Value = "07222222222"
                                },
                                new
                                {
                                    EmployeeId = 3,
                                    Value = "07333333333"
                                },
                                new
                                {
                                    EmployeeId = 4,
                                    Value = "07444444444"
                                },
                                new
                                {
                                    EmployeeId = 5,
                                    Value = "07555555555"
                                });
                        });

                    b.Navigation("Department");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("EmploymentPeriod")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.SupportTicket", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.Asset", "Asset")
                        .WithMany("SupportTickets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.Priority", "Priority")
                        .WithMany("SupportTickets")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.Resolution", "Resolution")
                        .WithMany("SupportTickets")
                        .HasForeignKey("ResolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.TicketStatus", "TicketStatus")
                        .WithMany("SupportTickets")
                        .HasForeignKey("TicketStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.User", null)
                        .WithMany("SupportTickets")
                        .HasForeignKey("UserId");

                    b.OwnsOne("ITAssetTracker.Domain.ValueObjects.DateRange", "ActivePeriod", b1 =>
                        {
                            b1.Property<int>("SupportTicketId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateOnly?>("end")
                                .HasColumnType("TEXT")
                                .HasColumnName("ClosedDate");

                            b1.Property<DateOnly>("start")
                                .HasColumnType("TEXT")
                                .HasColumnName("CreationDate");

                            b1.HasKey("SupportTicketId");

                            b1.ToTable("SupportTickets");

                            b1.WithOwner()
                                .HasForeignKey("SupportTicketId");

                            b1.HasData(
                                new
                                {
                                    SupportTicketId = 1,
                                    start = new DateOnly(2024, 6, 1)
                                },
                                new
                                {
                                    SupportTicketId = 2,
                                    end = new DateOnly(2024, 5, 12),
                                    start = new DateOnly(2024, 5, 10)
                                },
                                new
                                {
                                    SupportTicketId = 3,
                                    start = new DateOnly(2024, 6, 15)
                                },
                                new
                                {
                                    SupportTicketId = 4,
                                    end = new DateOnly(2024, 4, 6),
                                    start = new DateOnly(2024, 4, 5)
                                },
                                new
                                {
                                    SupportTicketId = 5,
                                    start = new DateOnly(2024, 6, 20)
                                });
                        });

                    b.Navigation("ActivePeriod")
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Employee");

                    b.Navigation("Priority");

                    b.Navigation("Resolution");

                    b.Navigation("TicketStatus");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.User", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Asset", b =>
                {
                    b.Navigation("AssetAssignments");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetProduct", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetStatus", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetType", b =>
                {
                    b.Navigation("AssetProducts");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Category", b =>
                {
                    b.Navigation("AssetTypes");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Employee", b =>
                {
                    b.Navigation("AssetAssignments");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Manufacturer", b =>
                {
                    b.Navigation("AssetProducts");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Priority", b =>
                {
                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Resolution", b =>
                {
                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.TicketStatus", b =>
                {
                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.User", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();

                    b.Navigation("SupportTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
