// <auto-generated />
using System;
using ITAssetTracker.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITAssetTracker.Persistence.Migrations
{
    [DbContext(typeof(ITAssetTrackerContext))]
    partial class ITAssetTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WarrantyExpiryDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AssetId");

                    b.HasIndex("AssetProductId");

                    b.HasIndex("AssetStatusId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetAssignment", b =>
                {
                    b.Property<int>("AssetAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AssetAssignmentId");

                    b.HasIndex("AssetId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AssetAssignments");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetHistory", b =>
                {
                    b.Property<int>("AssetHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AssetHistoryId");

                    b.HasIndex("AssetId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("AssetHistories");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetProduct", b =>
                {
                    b.Property<int>("AssetProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AssetProductId");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("AssetProducts");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetStatus", b =>
                {
                    b.Property<int>("AssetStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssetStatusId");

                    b.ToTable("AssetStatuses");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetType", b =>
                {
                    b.Property<int>("AssetTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AssetTypeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("AssetTypes");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Priority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PriorityId");

                    b.ToTable("Priorities");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Resolution", b =>
                {
                    b.Property<int>("ResolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ResolutionId");

                    b.ToTable("Resolutions");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.SupportTicket", b =>
                {
                    b.Property<int>("SupportTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResolutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SupportTicketId");

                    b.HasIndex("AssetId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("ResolutionId");

                    b.HasIndex("TicketStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.TicketAssignmentHistory", b =>
                {
                    b.Property<int>("TicketAssignmentHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupportTicketId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UnassignedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("TicketAssignmentHistoryId");

                    b.HasIndex("SupportTicketId");

                    b.ToTable("TicketAssignmentHistories");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.TicketStatus", b =>
                {
                    b.Property<int>("TicketStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("TicketStatusId");

                    b.ToTable("TicketStatuses");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Asset", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.AssetProduct", "AssetProducts")
                        .WithMany("Assets")
                        .HasForeignKey("AssetProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.AssetStatus", "AssetStatuses")
                        .WithMany("Assets")
                        .HasForeignKey("AssetStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetProducts");

                    b.Navigation("AssetStatuses");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetAssignment", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.Asset", "Asset")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.Employee", "Employee")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetHistory", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.Asset", "Asset")
                        .WithMany("AssetHistories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetProduct", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.AssetType", "AssetType")
                        .WithMany("AssetProducts")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("AssetProducts")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetType", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.Category", "Category")
                        .WithMany("AssetTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Employee", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("ITAssetTracker.Domain.Entities.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.SupportTicket", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.Asset", "Asset")
                        .WithMany("SupportTickets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.Priority", "Priority")
                        .WithMany("SupportTickets")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.Resolution", "Resolution")
                        .WithMany("SupportTickets")
                        .HasForeignKey("ResolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.TicketStatus", "TicketStatus")
                        .WithMany("SupportTickets")
                        .HasForeignKey("TicketStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetTracker.Domain.Entities.User", null)
                        .WithMany("SupportTickets")
                        .HasForeignKey("UserId");

                    b.Navigation("Asset");

                    b.Navigation("Employee");

                    b.Navigation("Priority");

                    b.Navigation("Resolution");

                    b.Navigation("TicketStatus");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.TicketAssignmentHistory", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.SupportTicket", "SupportTicket")
                        .WithMany("TicketAssignmentHistories")
                        .HasForeignKey("SupportTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.User", b =>
                {
                    b.HasOne("ITAssetTracker.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Asset", b =>
                {
                    b.Navigation("AssetAssignments");

                    b.Navigation("AssetHistories");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetProduct", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetStatus", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.AssetType", b =>
                {
                    b.Navigation("AssetProducts");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Category", b =>
                {
                    b.Navigation("AssetTypes");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Employee", b =>
                {
                    b.Navigation("AssetAssignments");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Manufacturer", b =>
                {
                    b.Navigation("AssetProducts");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Priority", b =>
                {
                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Resolution", b =>
                {
                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.SupportTicket", b =>
                {
                    b.Navigation("TicketAssignmentHistories");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.TicketStatus", b =>
                {
                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("ITAssetTracker.Domain.Entities.User", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();

                    b.Navigation("SupportTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
